# Generated by Django 5.1.4 on 2026-03-18 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('clinic_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('health_center', 'Health Center'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('specialist', 'Specialist Center')], default='clinic', max_length=20)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('county_district', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinics/logos/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Verification'), ('suspended', 'Suspended')], default='pending', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clinics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinics',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('lab_tech', 'Lab Technician'), ('pharmacist', 'Pharmacist'), ('admin', 'Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='clinics.clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinic_staff',
                'unique_together': {('clinic', 'user')},
            },
        ),
    ]
